runtime: php55
api_version: 1

handlers:
- url: /test/.*
  script: test.php

- url: /.*
  script: index.php

env_variables:
  MYSQL_DSN: mysql:unix_socket=/cloudsql/gitlabusers-mn2017:europe-west1:test1;dbname=dbtest
  MYSQL_USER: mike1
  MYSQL_PASSWORD: mike1